int transformAllThisSnakedToCamelCaseEvenWithBadMixedCase;
lass classNameShouldFollowStandardTemplateLibrayWithSnakeCase{};
voif functionNameShouldFollowStandardTemplateLibrayWithSnakeCase();
void snakeFunctionNameRemainUnchanged();
void camelCasedFunction();
void lowerCamelCasedFunction();
std::unorderedSet<myUnorderedSet> myCamelCaseMapNotOk;
int camelCaseVariable;
int snakeCaseVariable;
int weirdCase;
++snakeCase;
++camelCase;
++weirdCase;
